"""confirm large deletions across syncs

A scan that would tombstone most of a source used to be refused outright, which kept the
index safe from a broken connector but made a genuine bulk deletion applyable only by
hand-editing the database. These two tables hold the deletion instead: the exact set of
external ids one scan believes is gone, and how many consecutive scans have reported that
same set. The tombstones are applied when the count reaches the required confirmations.

Revision ID: 23307d6ab3a3
Revises: 5d8fa8b5147a
Create Date: 2026-07-27 18:53:37.899161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23307d6ab3a3'
down_revision: Union[str, Sequence[str], None] = '5d8fa8b5147a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_deletion_watches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('required', sa.Integer(), nullable=False),
    sa.Column('object_count', sa.Integer(), nullable=False),
    sa.Column('indexed_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_source_deletion_watch_source')
    )
    op.create_table('source_deletion_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('watch_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['source_deletion_watches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_deletion_candidates_watch', 'source_deletion_candidates', ['watch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_deletion_candidates_watch', table_name='source_deletion_candidates')
    op.drop_table('source_deletion_candidates')
    op.drop_table('source_deletion_watches')
    # ### end Alembic commands ###
