"""identity provider credentials

Revision ID: 5d8fa8b5147a
Revises: cc9ef5e3d206
Create Date: 2026-07-27 14:42:42.969127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d8fa8b5147a'
down_revision: Union[str, Sequence[str], None] = 'cc9ef5e3d206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_provider_credentials',
    sa.Column('alias', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('client_id', sa.String(length=512), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('key_fingerprint', sa.String(length=16), nullable=False),
    sa.Column('discovery_url', sa.Text(), nullable=False),
    sa.Column('extra_value', sa.Text(), nullable=True),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_ok', sa.Boolean(), nullable=True),
    sa.Column('last_test_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('alias')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('identity_provider_credentials')
    # ### end Alembic commands ###
