"""scheduler heartbeats

Revision ID: 6da0f927f868
Revises: 23307d6ab3a3
Create Date: 2026-07-28 14:25:25.415372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6da0f927f868'
down_revision: Union[str, Sequence[str], None] = '9c1d4e7f2a58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduler_heartbeats',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('beat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduler_heartbeats')
    # ### end Alembic commands ###
