#!/usr/bin/env bash
# The dummy environment the CI stack boots on.
#
# docker-compose.yml aborts on twelve `${VAR:?}` variables before it starts a single
# container, so a checkout with no environment cannot bring up even Postgres. CI needs
# those variables to exist; it does not need any of them to be real, because the job that
# uses this stack backs the estate up and reads it back and never calls a model.
#
# This is a script rather than a committed `.env.ci` because .gitignore excludes `.env.*`
# — a committed file by that name would be silently untracked, and CI would then run on
# whatever happened to be left in the runner's working directory. Generating it means the
# values are in version control (here) and the file is always exactly what this says.
#
# Every value below is deliberately obvious rubbish. Nothing here unlocks anything.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$(pwd -P)"

target="${1:-.env.ci}"

# Refuse to touch `.env`. That file holds a developer's real provider keys, and a stray
# `scripts/ci-env.sh` with no argument overwriting it would cost an afternoon and a key
# rotation. The CI stack is always started with `--env-file`, so it never needs `.env`.
case "$(basename "$target")" in
  .env)
    echo "ci-env.sh refuses to write .env — that file holds real keys. Pass another path." >&2
    exit 2
    ;;
esac

cat > "$target" <<ENV
# GENERATED by scripts/ci-env.sh. Dummy values for CI only — never a deployment.
#
# The twelve variables docker-compose.yml marks required with \${VAR:?} come first;
# without every one of them \`docker compose config\` fails and nothing starts.

# Provider credentials. LiteLLM validates neither at boot, so these are enough for the
# gateway to start, migrate its database and serve /health/liveliness — which is all CI
# asks of it. A model call with these would fail, and no CI job makes one.
KI_OPENAI_API_KEY=sk-ci-not-a-real-openai-key
KI_SCW_SECRET_KEY=ci-not-a-real-scaleway-key

# Model naming. Matched to the defaults in tests/conftest.py so a test that reads
# KI_LLM_MODEL sees the same string whether or not this file was loaded.
KI_LLM_MODEL=qwen3.6-35b-a3b
KI_LLM_UPSTREAM=openai/ci-not-a-real-model
KI_LLM_API_BASE=http://127.0.0.1:9/v1
KI_LLM_INPUT_COST_PER_TOKEN=0.0
KI_LLM_OUTPUT_COST_PER_TOKEN=0.0
KI_EMBEDDING_MODEL=text-embedding-3-small
KI_EMBEDDING_UPSTREAM=openai/ci-not-a-real-embedding-model
KI_EMBEDDING_INPUT_COST_PER_TOKEN=0.0

# Decodes to the ASCII string "ci-dummy-key-not-a-real-secret--", 32 bytes, which is what
# AES-256-GCM wants. Connector credentials encrypted under it in CI are throwaway.
KI_CONNECTOR_CREDENTIAL_KEY=Y2ktZHVtbXkta2V5LW5vdC1hLXJlYWwtc2VjcmV0LS0=
KI_RESTORE_AGENT_SECRET=ci-restore-agent-secret-not-a-real-secret

# ------------------------------------------------------------------ CI-only placement
#
# Absolute, both of them. The local-folder mount uses one variable for the host path and
# the container path, and a container path that is not absolute makes compose reject the
# service outright — with a message about the target, which sends you looking at the wrong
# half of the pair.
#
# The backup mount has to be a host directory this checkout owns for a second reason: the
# round-trip test finds it by inspecting the app container's mounts and refuses to run
# unless it is a directory it can write. A named volume there would skip the whole suite.
KI_LOCAL_MOUNT=${ROOT}/runtime/ci/local
KI_BACKUP_MOUNT=${ROOT}/runtime/ci/backups
ENV

echo "wrote $target"
